// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCk8dCNhNnFasHqK1ZD6oKaKGF9vPlcqA',
    appId: '1:1074559663961:web:565656248c170bc19e1648',
    messagingSenderId: '1074559663961',
    projectId: 'shoe-shop-c8799',
    authDomain: 'shoe-shop-c8799.firebaseapp.com',
    storageBucket: 'shoe-shop-c8799.firebasestorage.app',
    measurementId: 'G-627GF6BHV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDZD8Nx_hsuiqXh7kC4L82LfE6v3Zq6ocs',
      appId: '1:1074559663961:android:834ce614187b6c3f9e1648',
      messagingSenderId: '1074559663961',
      projectId: 'shoe-shop-c8799',
      storageBucket: 'shoe-shop-c8799.firebasestorage.app',
      measurementId: "G-PNN8EB50TK");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9LWdrWL23nGW9DRRPaYxotlseCOtxGY',
    appId: '1:1074559663961:ios:62732356853dab409e1648',
    messagingSenderId: '1074559663961',
    projectId: 'shoe-shop-c8799',
    storageBucket: 'shoe-shop-c8799.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9LWdrWL23nGW9DRRPaYxotlseCOtxGY',
    appId: '1:1074559663961:ios:62732356853dab409e1648',
    messagingSenderId: '1074559663961',
    projectId: 'shoe-shop-c8799',
    storageBucket: 'shoe-shop-c8799.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCk8dCNhNnFasHqK1ZD6oKaKGF9vPlcqA',
    appId: '1:1074559663961:web:cfedca79fc9be0619e1648',
    messagingSenderId: '1074559663961',
    projectId: 'shoe-shop-c8799',
    authDomain: 'shoe-shop-c8799.firebaseapp.com',
    storageBucket: 'shoe-shop-c8799.firebasestorage.app',
    measurementId: 'G-DVTBBSPXDB',
  );
}
